version: '3.8'

n8n:
  image: docker.n8n.io/n8nio/n8n
  restart: always
  ports:
    - 5678:5678
  links:
    - postgres
  volumes:
    - n8n_storage:/home/node/.n8n
  depends_on:
    postgres:
      condition: service_healthy

volumes:
  n8n_storage: