version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - 5678:5678
    environment:
      - N8N_LOG_LEVEL=silent
      - WEBHOOK_URL=https://your-webhook-url.com
      - N8N_QUEUE_TYPE=redis
      - N8N_QUEUE_HOST=redis
      - N8N_QUEUE_PORT=6379
      - N8N_QUEUE_NAME=n8n
      - EXECUTIONS_WORKER=true
      - EXECUTIONS_WORKER_NODES=3
    networks:
      - n8n
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=n8n
      - MYSQL_USER=n8n
      - MYSQL_PASSWORD=root123
    networks:
      - n8n

  redis:
    image: redis:latest
    networks:
      - n8n

  worker-1:
    image: n8nio/n8n:latest
    command: worker
    environment:
      - N8N_LOG_LEVEL=silent
      - N8N_QUEUE_TYPE=redis
      - N8N_QUEUE_HOST=redis
      - N8N_QUEUE_PORT=6379
      - N8N_QUEUE_NAME=n8n
      - EXECUTIONS_WORKER=true
      - EXECUTIONS_WORKER_NODES=1
    depends_on:
      - n8n
    networks:
      - n8n

  worker-2:
    image: n8nio/n8n:latest
    command: worker
    environment:
      - N8N_LOG_LEVEL=silent
      - N8N_QUEUE_TYPE=redis
      - N8N_QUEUE_HOST=redis
      - N8N_QUEUE_PORT=6379
      - N8N_QUEUE_NAME=n8n
      - EXECUTIONS_WORKER=true
      - EXECUTIONS_WORKER_NODES=1
    depends_on:
      - n8n
    networks:
      - n8n

  worker-3:
    image: n8nio/n8n:latest
    command: worker
    environment:
      - N8N_LOG_LEVEL=silent
      - N8N_QUEUE_TYPE=redis
      - N8N_QUEUE_HOST=redis
      - N8N_QUEUE_PORT=6379
      - N8N_QUEUE_NAME=n8n
      - EXECUTIONS_WORKER=true
      - EXECUTIONS_WORKER_NODES=1
    depends_on:
      - n8n
    networks:
      - n8n

networks:
  n8n:
    driver: bridge