version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/root/.n8n
    networks:
      - n8n

volumes:
  n8n_data:

networks:
  n8n: